apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
    app: v1
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
