apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx4
    app: v2
  name: nginx4
spec:
  containers:
  - image: nginx
    name: nginx4
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
