apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tainted-pod
  name: tainted-pod
spec:
  containers:
  - image: nginx
    name: tainted-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector: 
    kubernetes.io/hostname: minikube
  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"
status: {}
