apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: varlog
          mountPath: /var/log/nginx 
    - name: logger
      image: busybox
      command: ['sh', '-c', 'while true; do echo "$(date) :: log" >> /var/log/app.log; sleep 5; done']
      volumeMounts:
        - name: varlog
          mountPath: /var/log 
  volumes:
    - name: varlog
      emptyDir: {}