apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-busy
  name: multi-busy
spec:
  containers:
  - image: busybox
    name: busy1
    command: 
      - "sh"
      - "-c"
      - "echo hello > /tmp/hello.txt; sleep 3600"
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /tmp
  - image: busybox
    name: busy2
    command: 
      - "sh"
      - "-c"
      - "sleep 3600"
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: shared-data
    emptyDir: {}  
status: {}
