apiVersion: v1
kind: Pod
metadata:
  labels:
    run: resource-test
  name: resource-test
spec:
  containers:
  - image: busybox
    name: resource-test
    resources: 
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    command: 
      - "sh"
      - "-c"
      - "sleep 3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
