apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nginx","namespace":"mynamespace"},"spec":{"containers":[{"image":"nginx:latest","name":"nginx"}]}}
  name: nginx
  namespace: mynamespace
spec:
  containers:
  - image: nginx:latest
    name: nginx
