apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busyb
  name: busyb
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo 'hello from container 1'; sleep 300
    image: busybox
    name: busyb-1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - echo 'hello from container 2'; sleep 300
    image: busybox
    name: busyb-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
