apiVersion: v1
kind: Pod
metadata:
  labels:
    run: box
  name: box
spec:


  initContainers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - echo 'Test' > /work-dir/index.html
    volumeMounts:
    - mountPath: /work-dir
      name: work-dir


  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: work-dir

      
  resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: work-dir
    emptyDir: {} 
status: {}
